### ISSUE TITLE
"*" is always interpreted as italic although it might be a bullet

### ISSUE THREAD

**Issue by patrickunterwegs** [ArnyminerZ/MarkdownText#12]
Hey @ArnyminerZ !
A user reported an issue with the markdown handling (regrettably as a confidential issue), the problem is when a list is not started with the "-" character but with the "*" character, the whole line is interpreted as italic instead of being an unordered list. 

I guess an additional check is necessary if there is an opening AND a closing character for "*" or if there is only the "*" character at the beginning of the line.

I might also have a look at it in the next days unless you're faster 😉

**Comment by patrickunterwegs** [comment]
Okok, it seems a bit tougher than I thought, as there are combinations possible like having an unordered list and *bold* formatting combined. But others just also seem to check if the line starts with an asterisk, if yes, interpret it as unordered list, then check the remaining asterisk characters in the line to update the formatting.

**Comment by ArnyminerZ** [comment]
> Okok, it seems a bit tougher than I thought, as there are combinations possible like having an unordered list and _bold_ formatting combined. But others just also seem to check if the line starts with an asterisk, if yes, interpret it as unordered list, then check the remaining asterisk characters in the line to update the formatting.

Yeah, that's why I didn't add this in the first place. I'm currently in exams period, but whenever I have some time I will take a look at this 😉

**Comment by patrickunterwegs** [comment]
thanks and good luck for your exams 😉

**Comment by ArnyminerZ** [comment]
I've been thinking about this, and the fastest fix I can think about is by considering as "required" to have an space after the `*` character for unordered lists. This way we can check if the like starts with `* `, which would not conflict with neither bold nor italics.

**Comment by ArnyminerZ** [comment]
Superseed by #14

**Comment by patrickunterwegs** [comment]
Yes, that also sounds like a nice solution for now 👍 🙂

**Comment by ArnyminerZ** [comment]
Closed by #14

**Comment by patrickunterwegs** [comment]
Hey @ArnyminerZ , would you mind preparing a new version with this fix/workaround? I'd like to make a new jtx version and it would be great if this could be included 🙂

**Comment by ArnyminerZ** [comment]
> Hey @ArnyminerZ , would you mind preparing a new version with this fix/workaround? I'd like to make a new jtx version and it would be great if this could be included 🙂 

Okay, don't worry, I'll try to release this tonight.

**Comment by ArnyminerZ** [comment]
Okay, it has been released. It'll take some time to appear. Maybe half an hour or so.

**Comment by patrickunterwegs** [comment]
Thanks a lot 🥳
