### ISSUE TITLE
[BUG] Text links without markdown tags disappear

### ISSUE THREAD

**Issue by patrickunterwegs** [ArnyminerZ/MarkdownText#47]
Hey @ArnyminerZ , 
I have just checked 1.3.0, thanks for the update! 
I did a test with the following text: 

> hello, 
this is now a markdown
https://www.orf.at
test
[https://www.orf.at](https://www.orf.at)
**asdf**

But when I show it as MarkdownText, the link is just disappearing: 

![Screenshot_1676151929](https://user-images.githubusercontent.com/72232737/218282450-753fe03d-2fef-46bb-b018-2caad848691e.png)

Could you have a look at this?

**Comment by ArnyminerZ** [comment]
I understand this happens with duplicated links?

**Comment by patrickunterwegs** [comment]
Nope, it doesn't matter if there are multiple link or if they are duplicates, the text only links just disappear
