### ISSUE TITLE
[Bug/Enhancement] suppress onClick when clicking on link

### ISSUE THREAD

**Issue by patrickunterwegs** [ArnyminerZ/MarkdownText#48]
Hey @ArnyminerZ !
Thank you for the change in #45, this was actually also necessary for jtx Board: 
When clicking on the text in the detail view, the screen would also change to the edit view. BUT the MarkdownText in 1.2.x suppressed the onClick method that was defined on the card. 
Now in 1.3.0 I used the onClick method of MarkdownText which works great. But when I click on a link that was defined with markdown tags, the link opens correctly, but also the onClick method is called (which for jtx Board would change the view mode to edit mode). I think this not an expected behaviour for the user. 
Could you suppress the onClick call when a markdown link is clicked?

**Comment by ArnyminerZ** [comment]
Sorry, I forgot about this, you have to set `onClickOverrides = true`. This way the default behavior is ignored.

**Comment by patrickunterwegs** [comment]
I have seen the onClickOverrides = true parameter, but I don't want the onClick function to completely suppress possibility to click on the link. I actually want to suppress the onClick function when a link is clicked...

**Comment by ArnyminerZ** [comment]
Mmmmh... I can set that when

**Comment by ArnyminerZ** [comment]
I'll make that when you click a link, if `onClick` has not been specified or `onClickOverrides` is false, the url is launched. If clicked something else, simple `onClick` is executed.

**Comment by patrickunterwegs** [comment]
Thanks @ArnyminerZ , I think it's the perfect solution now 🙂
